### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by naliio** [DNA-and-Natural-Algorithms-Group/multistrand#37]
Hi,

I'm trying to install the multistrand on Linux, but my system always automatically invokes python3 of anaconda3. Therefore, when I input "make install", it reported the following error:
<img width="769" alt="0440b58366422ae203de5f0078f9385" src="https://github.com/DNA-and-Natural-Algorithms-Group/multistrand/assets/114900887/966abbb8-14bd-44ff-a04f-18a9f49cbf44">

In fact, there is python2 in my system:

>**(base) [nli@mgt01 dna]$** which python2
>/usr/bin/python2
>**(base) [nli@mgt01 dna]$** python2 -V
>Python 2.7.5

Could you please tell me how to invoke python2 to install the multistrand? Thank you.

**Comment by the-casle** [comment]
Your conda env you created is with python3 instead of python2. You can create a conda env with the correct version using:

`conda create --name <env_name> python= 2.7.18`

I have an updated fork that is compatible python3 if you want to try that out, too.

**Comment by naliio** [comment]
Thank you very much. I created a conda env as you said and now the multistrand can run normally.
